title: Indoicle
author:
  name: Matthijs Alderliefste
  email: 'm@mateis.nl'
metadata:
  description: 'A ‘Fast-food content’ website for the Indonesian market'
  author: Matres
taxonomies: [category, tag]
